DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS files;

CREATE TABLE links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT UNIQUE NOT NULL,
    hash TEXT NOT NULL,
    created_at DATETIME,
    expires_at DATETIME
);

CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    link_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    uuid TEXT UNIQUE NOT NULL,
    FOREIGN KEY(link_id) REFERENCES links(id)
);